name: Build obsidian plugin

on:
  push:
    branches:
      - master
env:
  PLUGIN_NAME: tag-page-preview # Change this to the name of your plugin-id folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x" # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          npm install
          npm run build --if-present
          npm run release
